[versions]
agp = "8.12.1"
kotlin = "1.9.24"
googleServices = "4.4.2" # Added Google Services version

[libraries]
# No changes needed in this section for this specific issue

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" } # Added Google Services plugin
